### ISSUE TITLE
After the update to 2.8.0 I keep getting the following errors:

### ISSUE THREAD

**Issue by neerajcse** [cometd/cometd-tutorials#1]
2014-03-11 00:04:54.277:WARN:oejw.WebSocketConnectionRFC6455:java.lang.NoSuchMet
hodError: org.cometd.server.ServerSessionImpl.isQueueEmpty()Z for SCEP@324a9b4a{
l(/0:0:0:0:0:0:0:1:52853)<->r(/0:0:0:0:0:0:0:1:8080),s=1,open=true,ishut=false,o
shut=false,rb=false,wb=false,w=true,i=1r}-{WebSocketServletConnectionRFC6455 p=W
ebSocketParserRFC6455@35e473f7 state=DATA buffer= g=WebSocketGeneratorRFC6455@29
7978c5 closed=false buffer=-1} java.lang.NoSuchMethodError: org.cometd.server.Se
rverSessionImpl.isQueueEmpty()Z
2014-03-11 00:05:00.961:WARN:oejw.WebSocketConnectionRFC6455:java.lang.NoSuchMet
hodError: org.cometd.server.ServerSessionImpl.isQueueEmpty()Z for SCEP@1945593d{
l(/0:0:0:0:0:0:0:1:52854)<->r(/0:0:0:0:0:0:0:1:8080),s=1,open=true,ishut=false,o
shut=false,rb=false,wb=false,w=true,i=1r}-{WebSocketServletConnectionRFC6455 p=W
ebSocketParserRFC6455@6cd1cb28 state=DATA buffer= g=WebSocketGeneratorRFC6455@41
70e6e8 closed=false buffer=-1} java.lang.NoSuchMethodError: org.cometd.server.Se
rverSessionImpl.isQueueEmpty()Z
## MAVEN VERSION:

Picked up _JAVA_OPTIONS: -Xmx512M
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T09:37:5
2-08:00)
Maven home: C:\Program Files\Apache Software Foundation\apache-maven-3.2.1
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_45\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
## COMETD VERSION:

2.8.0

**Comment by sbordet** [comment]
Thank you for reporting this problem. It was due to the dependency with the tutorials skeleton project not being up to date.
I have updated the tutorials skeleton project to the latest CometD version, and updated these tutorials to reference the latest skeleton.
I tested it and works for me. You may need to wait some time for the skeleton update to appear on Maven Central.
